VOL-2180: Introducing AWS Cognito User Migration Lambda (LDAP)
dvsa/cognito-migration-lambda pull request #1
Opened 2021-08-13 11:34 UTC by jerotire

## Description

Introduces the User Migration Lambda for use by AWS Cognito. The lambda accepts an event from AWS Cognito (forgotten password or authentication) and attempts to either fetch a user (forgotten password journey) or authenticates a user (authentication journey) against an LDAP service. The response from the lambda will instruct AWS Cognito to create a user (migrate them) or throw an exception (User Not Found or Invalid Credentials).

Related issue: VOL-2180

## Type of change
Feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works

2021-08-16 07:54 UTC, sdh100shaun approved these changes

2021-08-16 13:06 UTC, Hodgy commented on src/util/logger.ts
> +  public trace(msg: string, ...args): void {
Worth pulling this into the starter as well?

2021-08-16 13:09 UTC, Hodgy commented on template.yaml
> +  HelloWorldFunctionIamRole:
Name?

2021-08-16 13:09 UTC, Hodgy commented on template.yaml
> +    Value: !GetAtt HelloWorldFunction.Arn
Name?

2021-08-16 13:23 UTC, jerotire commented on template.yaml
> +    Value: !GetAtt HelloWorldFunction.Arn
Nice spot.

2021-08-16 13:23 UTC, jerotire commented on template.yaml
> +  HelloWorldFunctionIamRole:
Nice spot 😄

2021-08-17 09:51 UTC, JoshuaLicense requested changes

2021-08-17 09:51 UTC, JoshuaLicense commented on event/userMigrationAuthenticationTriggerEvent.event.json
> +    "finalUserStatus": "Nope",
Would these be better as valid values? `UNKNOWN` & `SUPPRESS`?

2021-08-17 09:51 UTC, JoshuaLicense commented on package-lock.json
>    "version": "1.0.0",
Quite minor in this case, but using npm v7 (making this `version: "2.0.0"`) will give better performance ([source](https://user-images.githubusercontent.com/459713/105940574-a1d5c880-6029-11eb-8461-9b57bff84c08.png)) while doing _most_ npm commands.

2021-08-17 09:51 UTC, JoshuaLicense commented on src/service/ldapUserStoreService.ts
> +      url: process.env.LDAP_URL,
Would timeouts being specified be a good idea here - `timeout` and `connectTimeout`? The default to `timeout` is currently infinity.

2021-08-17 12:02 UTC, jerotire commented on src/util/logger.ts
> +  public trace(msg: string, ...args): void {
Yup, I'll make a new PR for that on the Lambda Starter.

2021-08-17 12:15 UTC, jerotire commented on src/util/logger.ts
> +  public trace(msg: string, ...args): void {
Done. PR created (https://github.com/dvsa/dvsa-lambda-starter/pull/47)

2021-08-17 12:29 UTC, jerotire commented on package-lock.json
>    "version": "1.0.0",
Are we talking about the **version** or **lockfileVersion**? The **version** is just duplicated from the version defined in `package.json`.

Look at this, I think we mean **lockFileVersion**? That's just an integer, and NPM did that automattically.
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

I've installed NPM v7, to get the new format for the lock file.

2021-08-17 12:46 UTC, JoshuaLicense commented on package-lock.json
>    "version": "1.0.0",
Yup `lockfileVersion` - clicked on the wrong line.

2021-08-17 14:13 UTC, jerotire commented on src/service/ldapUserStoreService.ts
> +      url: process.env.LDAP_URL,
I think we can benefit with a "timeout" being specified, maybe even with it being definable from `process.env`.

2021-08-18 12:13 UTC, jerotire commented on event/userMigrationAuthenticationTriggerEvent.event.json
> +    "finalUserStatus": "Nope",
Yup, I'll remove them as they are set by the lambda.

2021-08-18 12:25 UTC, JoshuaLicense approved these changes

2021-08-18 12:29 UTC, sdh100shaun approved these changes

2021-08-18 12:30 UTC, sdh100shaun commented
@jerotire  can we update the AWS sdk please see https://github.com/dvsa/cognito-migration-lambda/pull/2 and double-check before merge

2021-08-18 12:45 UTC, jerotire commented
> @jerotire can we update the AWS sdk please see #2 and double-check before merge

Yup, only required for dev dependancies, not for Production.

With the NPM update, I also ran npm update, and we now have `"aws-sdk": "^2.969.0",` which surpasses the one defined by Snyk in #2.

2021-08-19 08:50 UTC, Hodgy approved these changes

2021-08-19 09:21 UTC, merged